### ISSUE TITLE
helm-purpose-switch-buffer-with-some-purpose should be able to create new buffer

### ISSUE THREAD

**Issue by tuhdo** [bmag/helm-purpose#1]
At the moment, this command cannot create a new buffer the way `helm-buffers-list` does. To enable buffer creation, this command needs to include the source `helm-source-buffer-not-found`.

**Comment by bmag** [comment]
Thanks, that's an interesting suggestion. The source `helm-source-buffer-not-found` lets the user create an arbitrary buffer, right? So the created buffer is *not guaranteed to have the same purpose* as the listed buffers. Is that your intention?

**Comment by tuhdo** [comment]
Well, since this is `helm-purpose`, there should be a new similar source that creates a buffer and gives it a purpose automatically. That's what I thougt.

**Comment by bmag** [comment]
Well, purposes are determined automatically by buffer name and major mode. There isn't any special property that says "this buffer has <some purpose>".
I could add a source that creates a dummy buffer (`*pu-dummy-<some-purpose>*`) with the correct purpose, but I'm not sure it's useful.

**Comment by tuhdo** [comment]
When you create a new buffer with `helm-buffers-list`, it automatically puts a buffer in a major mode based on the extension. If `purposes` can determine a buffer based on its major mode, then adding `helm-source-buffer-not-found` should suffice.

**Comment by bmag** [comment]
Added in https://github.com/bmag/helm-purpose/commit/9ff4c21c1e9ebc7afb851b738f815df7343bb287
